[TT-3722] Fixes apps cred
TykTechnologies/raava-admin pull request #56
Opened 2021-12-03 18:50 UTC by cmelgarejo

2021-12-09 09:55 UTC, ConsM commented on views/metas/form/action_button.tmpl
> +</div>
It seems you've mixed up some CSS classes, `modal fade`, `p-{number}` and `justify-content-center` for example are Bootstrap ones, which is not used in the admin app.

2021-12-09 09:55 UTC, ConsM commented on views/metas/form/reveal.tmpl
> +<div class="mdl-textfield mdl-textfield--full-width mdl-js-textfield tyk-form-group--rounded-corners">
are the `mdl-` classes needed ?

2021-12-09 09:57 UTC, ConsM requested changes
I've left a couple of comments. 
On a separate note, the script that reveals the value should be refactored but it works for now so as discussed and agreed with Christian we can merge this now and i will refactor it later via [this](https://tyktech.atlassian.net/browse/TT-4108)

2021-12-13 19:30 UTC, padiazg approved these changes
LGTM

2021-12-13 19:30 UTC, merged